package com.velebit.anippe.shared.reminders;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractFormFieldData;
import org.eclipse.scout.rt.shared.data.form.fields.tablefield.AbstractTableFieldBeanData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

import javax.annotation.Generated;
import java.util.Date;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "com.velebit.anippe.client.reminders.AbstractRemindersGroupBox", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public abstract class AbstractRemindersGroupBoxData extends AbstractFormFieldData {
    private static final long serialVersionUID = 1L;

    /**
     * access method for property RelatedId.
     */
    public Integer getRelatedId() {
        return getRelatedIdProperty().getValue();
    }

    /**
     * access method for property RelatedId.
     */
    public void setRelatedId(Integer relatedId) {
        getRelatedIdProperty().setValue(relatedId);
    }

    public RelatedIdProperty getRelatedIdProperty() {
        return getPropertyByClass(RelatedIdProperty.class);
    }

    /**
     * access method for property RelatedType.
     */
    public Integer getRelatedType() {
        return getRelatedTypeProperty().getValue();
    }

    /**
     * access method for property RelatedType.
     */
    public void setRelatedType(Integer relatedType) {
        getRelatedTypeProperty().setValue(relatedType);
    }

    public RelatedTypeProperty getRelatedTypeProperty() {
        return getPropertyByClass(RelatedTypeProperty.class);
    }

    public RemindersTable getRemindersTable() {
        return getFieldByClass(RemindersTable.class);
    }

    public static class RelatedIdProperty extends AbstractPropertyData<Integer> {
        private static final long serialVersionUID = 1L;
    }

    public static class RelatedTypeProperty extends AbstractPropertyData<Integer> {
        private static final long serialVersionUID = 1L;
    }

    public static class RemindersTable extends AbstractTableFieldBeanData {
        private static final long serialVersionUID = 1L;

        @Override
        public RemindersTableRowData addRow() {
            return (RemindersTableRowData) super.addRow();
        }

        @Override
        public RemindersTableRowData addRow(int rowState) {
            return (RemindersTableRowData) super.addRow(rowState);
        }

        @Override
        public RemindersTableRowData createRow() {
            return new RemindersTableRowData();
        }

        @Override
        public Class<? extends AbstractTableRowData> getRowType() {
            return RemindersTableRowData.class;
        }

        @Override
        public RemindersTableRowData[] getRows() {
            return (RemindersTableRowData[]) super.getRows();
        }

        @Override
        public RemindersTableRowData rowAt(int index) {
            return (RemindersTableRowData) super.rowAt(index);
        }

        public void setRows(RemindersTableRowData[] rows) {
            super.setRows(rows);
        }

        public static class RemindersTableRowData extends AbstractTableRowData {
            private static final long serialVersionUID = 1L;
            public static final String reminder = "reminder";
            public static final String createdAt = "createdAt";
            public static final String remindAt = "remindAt";
            public static final String userCreated = "userCreated";
            public static final String title = "title";
            public static final String user = "user";
            public static final String content = "content";
            public static final String sendEmail = "sendEmail";
            private Reminder m_reminder;
            private Date m_createdAt;
            private Date m_remindAt;
            private String m_userCreated;
            private String m_title;
            private String m_user;
            private String m_content;
            private Boolean m_sendEmail;

            public Reminder getReminder() {
                return m_reminder;
            }

            public void setReminder(Reminder newReminder) {
                m_reminder = newReminder;
            }

            public Date getCreatedAt() {
                return m_createdAt;
            }

            public void setCreatedAt(Date newCreatedAt) {
                m_createdAt = newCreatedAt;
            }

            public Date getRemindAt() {
                return m_remindAt;
            }

            public void setRemindAt(Date newRemindAt) {
                m_remindAt = newRemindAt;
            }

            public String getUserCreated() {
                return m_userCreated;
            }

            public void setUserCreated(String newUserCreated) {
                m_userCreated = newUserCreated;
            }

            public String getTitle() {
                return m_title;
            }

            public void setTitle(String newTitle) {
                m_title = newTitle;
            }

            public String getUser() {
                return m_user;
            }

            public void setUser(String newUser) {
                m_user = newUser;
            }

            public String getContent() {
                return m_content;
            }

            public void setContent(String newContent) {
                m_content = newContent;
            }

            public Boolean getSendEmail() {
                return m_sendEmail;
            }

            public void setSendEmail(Boolean newSendEmail) {
                m_sendEmail = newSendEmail;
            }
        }
    }
}
