package com.velebit.anippe.shared.tasks;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractFormFieldData;
import org.eclipse.scout.rt.shared.data.form.fields.tablefield.AbstractTableFieldBeanData;
import org.eclipse.scout.rt.shared.data.form.properties.AbstractPropertyData;

import javax.annotation.Generated;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "com.velebit.anippe.client.tasks.AbstractTasksGroupBox", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public abstract class AbstractTasksGroupBoxData extends AbstractFormFieldData {
    private static final long serialVersionUID = 1L;

    /**
     * access method for property RelatedId.
     */
    public Integer getRelatedId() {
        return getRelatedIdProperty().getValue();
    }

    /**
     * access method for property RelatedId.
     */
    public void setRelatedId(Integer relatedId) {
        getRelatedIdProperty().setValue(relatedId);
    }

    public RelatedIdProperty getRelatedIdProperty() {
        return getPropertyByClass(RelatedIdProperty.class);
    }

    /**
     * access method for property RelatedType.
     */
    public Integer getRelatedType() {
        return getRelatedTypeProperty().getValue();
    }

    /**
     * access method for property RelatedType.
     */
    public void setRelatedType(Integer relatedType) {
        getRelatedTypeProperty().setValue(relatedType);
    }

    public RelatedTypeProperty getRelatedTypeProperty() {
        return getPropertyByClass(RelatedTypeProperty.class);
    }

    public TasksTable getTasksTable() {
        return getFieldByClass(TasksTable.class);
    }

    public static class RelatedIdProperty extends AbstractPropertyData<Integer> {
        private static final long serialVersionUID = 1L;
    }

    public static class RelatedTypeProperty extends AbstractPropertyData<Integer> {
        private static final long serialVersionUID = 1L;
    }

    public static class TasksTable extends AbstractTableFieldBeanData {
        private static final long serialVersionUID = 1L;

        @Override
        public TasksTableRowData addRow() {
            return (TasksTableRowData) super.addRow();
        }

        @Override
        public TasksTableRowData addRow(int rowState) {
            return (TasksTableRowData) super.addRow(rowState);
        }

        @Override
        public TasksTableRowData createRow() {
            return new TasksTableRowData();
        }

        @Override
        public Class<? extends AbstractTableRowData> getRowType() {
            return TasksTableRowData.class;
        }

        @Override
        public TasksTableRowData[] getRows() {
            return (TasksTableRowData[]) super.getRows();
        }

        @Override
        public TasksTableRowData rowAt(int index) {
            return (TasksTableRowData) super.rowAt(index);
        }

        public void setRows(TasksTableRowData[] rows) {
            super.setRows(rows);
        }

        public static class TasksTableRowData extends AbstractTableRowData {
            private static final long serialVersionUID = 1L;
        }
    }
}
