package com.velebit.anippe.shared;

import org.eclipse.scout.rt.shared.data.basic.table.AbstractTableRowData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractFormFieldData;
import org.eclipse.scout.rt.shared.data.form.fields.AbstractValueFieldData;
import org.eclipse.scout.rt.shared.data.form.fields.tablefield.AbstractTableFieldBeanData;

import javax.annotation.Generated;
import java.util.Date;

/**
 * <b>NOTE:</b><br>
 * This class is auto generated by the Scout SDK. No manual modifications recommended.
 */
@Generated(value = "com.velebit.anippe.client.tasks.AbstractCheckListGroupBox", comments = "This class is auto generated by the Scout SDK. No manual modifications recommended.")
public abstract class AbstractCheckListGroupBoxData extends AbstractFormFieldData {
    private static final long serialVersionUID = 1L;

    public ChildTasksProgress getChildTasksProgress() {
        return getFieldByClass(ChildTasksProgress.class);
    }

    public SubTasksTable getSubTasksTable() {
        return getFieldByClass(SubTasksTable.class);
    }

    public static class ChildTasksProgress extends AbstractValueFieldData<String> {
        private static final long serialVersionUID = 1L;
    }

    public static class SubTasksTable extends AbstractTableFieldBeanData {
        private static final long serialVersionUID = 1L;

        @Override
        public SubTasksTableRowData addRow() {
            return (SubTasksTableRowData) super.addRow();
        }

        @Override
        public SubTasksTableRowData addRow(int rowState) {
            return (SubTasksTableRowData) super.addRow(rowState);
        }

        @Override
        public SubTasksTableRowData createRow() {
            return new SubTasksTableRowData();
        }

        @Override
        public Class<? extends AbstractTableRowData> getRowType() {
            return SubTasksTableRowData.class;
        }

        @Override
        public SubTasksTableRowData[] getRows() {
            return (SubTasksTableRowData[]) super.getRows();
        }

        @Override
        public SubTasksTableRowData rowAt(int index) {
            return (SubTasksTableRowData) super.rowAt(index);
        }

        public void setRows(SubTasksTableRowData[] rows) {
            super.setRows(rows);
        }

        public static class SubTasksTableRowData extends AbstractTableRowData {
            private static final long serialVersionUID = 1L;
            public static final String childTaskId = "childTaskId";
            public static final String completedAt = "completedAt";
            public static final String completed = "completed";
            public static final String createdAt = "createdAt";
            public static final String createdBy = "createdBy";
            public static final String task = "task";
            public static final String actions = "actions";
            private Integer m_childTaskId;
            private Date m_completedAt;
            private Boolean m_completed;
            private Date m_createdAt;
            private String m_createdBy;
            private String m_task;
            private String m_actions;

            public Integer getChildTaskId() {
                return m_childTaskId;
            }

            public void setChildTaskId(Integer newChildTaskId) {
                m_childTaskId = newChildTaskId;
            }

            public Date getCompletedAt() {
                return m_completedAt;
            }

            public void setCompletedAt(Date newCompletedAt) {
                m_completedAt = newCompletedAt;
            }

            public Boolean getCompleted() {
                return m_completed;
            }

            public void setCompleted(Boolean newCompleted) {
                m_completed = newCompleted;
            }

            public Date getCreatedAt() {
                return m_createdAt;
            }

            public void setCreatedAt(Date newCreatedAt) {
                m_createdAt = newCreatedAt;
            }

            public String getCreatedBy() {
                return m_createdBy;
            }

            public void setCreatedBy(String newCreatedBy) {
                m_createdBy = newCreatedBy;
            }

            public String getTask() {
                return m_task;
            }

            public void setTask(String newTask) {
                m_task = newTask;
            }

            public String getActions() {
                return m_actions;
            }

            public void setActions(String newActions) {
                m_actions = newActions;
            }
        }
    }
}
